import type { Category, Product, GalleryItem, StoreSettings } from "./lib/types";

export const defaultCategories: Category[] = [
  { id: "cat-freshwater", name: "Freshwater Fish", slug: "freshwater-fish", sort_order: 1 },
  { id: "cat-marine", name: "Marine Fish", slug: "marine-fish", sort_order: 2 },
  { id: "cat-plants", name: "Aquatic Plants", slug: "aquatic-plants", sort_order: 3 },
  { id: "cat-tanks", name: "Tanks & Accessories", slug: "tanks-accessories", sort_order: 4 },
  { id: "cat-food", name: "Fish Food", slug: "fish-food", sort_order: 5 },
  { id: "cat-care", name: "Care & Health", slug: "care-health", sort_order: 6 },
];

export const defaultProducts: Product[] = [
  // --- Freshwater Fish ---
  {
    id: "prod-albino-bichir",
    name: "Albino Bichir (Polypterus senegalus)",
    category_id: "cat-freshwater",
    price: 450,
    unit: "per fish",
    description: "Our signature mascot! Prehistoric dinosaur eel with dragon-like dorsal finlets, velvety golden-amber scales, and bright ruby eyes. Hardy, peaceful, and fascinating to watch gliding along the tank floor.",
    tag: "Store Mascot",
    image_url: "https://images.pexels.com/photos/31956913/pexels-photo-31956913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 1,
    categories: defaultCategories[0],
    scientific_name: "Polypterus senegalus (Albino)",
    care_level: "Intermediate",
    water_type: "Freshwater",
    temperament: "Peaceful",
    temp_range: "25°C - 28°C",
    ph_range: "6.8 - 7.5",
    min_tank_size: "100 Litres",
    diet: "Carnivore (Sinking pellets, bloodworms, small shrimp)",
  },
  {
    id: "prod-red-oscar",
    name: "Red Tiger Oscar (Fire Cichlid)",
    category_id: "cat-freshwater",
    price: 280,
    unit: "per fish",
    description: "Featured in our logo! Highly intelligent, charismatic 'water dog' with fiery crimson and obsidian patterns. Recognized by hobbyists for interacting directly with their owners during feeding time.",
    tag: "Featured in Logo",
    image_url: "https://images.pexels.com/photos/18435511/pexels-photo-18435511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 2,
    categories: defaultCategories[0],
    scientific_name: "Astronotus ocellatus",
    care_level: "Easy",
    water_type: "Freshwater",
    temperament: "Semi-Aggressive",
    temp_range: "24°C - 28°C",
    ph_range: "6.5 - 7.2",
    min_tank_size: "150 Litres",
    diet: "Omnivore / Carnivore (Cichlid pellets, dried krill)",
  },
  {
    id: "prod-golden-severum",
    name: "Golden Severum (Gold Discus-Cichlid)",
    category_id: "cat-freshwater",
    price: 320,
    unit: "per fish",
    description: "The third iconic fish from our emblem! Glowing canary-yellow disc body with delicate crimson speckles. Known as the 'poor man's discus' due to its regal shape and peaceful community temperament.",
    tag: "Logo Special",
    image_url: "https://images.pexels.com/photos/31807563/pexels-photo-31807563.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 3,
    categories: defaultCategories[0],
    scientific_name: "Heros efasciatus (Gold)",
    care_level: "Easy",
    water_type: "Freshwater",
    temperament: "Peaceful",
    temp_range: "25°C - 29°C",
    ph_range: "6.0 - 7.0",
    min_tank_size: "120 Litres",
    diet: "Omnivore (Spirulina flakes, micropellets, blanched peas)",
  },
  {
    id: "prod-neon-tetra",
    name: "Neon Tetra (Cardinals)",
    category_id: "cat-freshwater",
    price: 40,
    unit: "per pair",
    description: "Electrifying iridescent blue and scarlet red schooling fish. Spectacular when swimming in groups of 6 or more in planted aquascapes.",
    tag: "Bestseller",
    image_url: "https://images.pexels.com/photos/18435511/pexels-photo-18435511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 4,
    categories: defaultCategories[0],
    scientific_name: "Paracheirodon innesi",
    care_level: "Easy",
    water_type: "Freshwater",
    temperament: "Schooling",
    temp_range: "22°C - 26°C",
    ph_range: "6.0 - 7.0",
    min_tank_size: "30 Litres",
    diet: "Omnivore (Micro flakes, baby brine shrimp)",
  },
  {
    id: "prod-fancy-guppy",
    name: "Fancy Dumbo Ear Guppy",
    category_id: "cat-freshwater",
    price: 35,
    unit: "per fish",
    description: "Vibrant livebearers boasting delta tails with metallic shimmer and oversized pectoral fins. Active, hardy, and beginner friendly.",
    tag: "Beginner Friendly",
    image_url: "https://images.pexels.com/photos/18435512/pexels-photo-18435512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 5,
    categories: defaultCategories[0],
    scientific_name: "Poecilia reticulata",
    care_level: "Easy",
    water_type: "Freshwater",
    temperament: "Peaceful",
    temp_range: "22°C - 28°C",
    ph_range: "7.0 - 8.2",
    min_tank_size: "20 Litres",
    diet: "Omnivore (Tropical flakes, spirulina)",
  },
  {
    id: "prod-clown-loach",
    name: "Clown Loach",
    category_id: "cat-freshwater",
    price: 120,
    unit: "per fish",
    description: "Playful tiger-striped bottom dwellers with bright orange fins. Natural biological control for pest snails and lovable tank comedians.",
    tag: "Pest Snail Eater",
    image_url: "https://images.pexels.com/photos/31956913/pexels-photo-31956913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 6,
    categories: defaultCategories[0],
    scientific_name: "Chromobotia macracanthus",
    care_level: "Intermediate",
    water_type: "Freshwater",
    temperament: "Peaceful",
    temp_range: "25°C - 30°C",
    ph_range: "6.5 - 7.5",
    min_tank_size: "150 Litres",
    diet: "Omnivore (Sinking wafers, bloodworms)",
  },
  {
    id: "prod-blue-discus",
    name: "Cobalt Blue Diamond Discus",
    category_id: "cat-freshwater",
    price: 950,
    unit: "per fish",
    description: "The King of the Aquarium. Magnificent pure metallic cobalt blue coloration with velvet sheen. Acclimated to clean, soft, warm water.",
    tag: "King of Aquarium",
    image_url: "https://images.pexels.com/photos/31807563/pexels-photo-31807563.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 7,
    categories: defaultCategories[0],
    scientific_name: "Symphysodon aequifasciatus",
    care_level: "Expert",
    water_type: "Freshwater",
    temperament: "Peaceful",
    temp_range: "28°C - 31°C",
    ph_range: "6.0 - 6.8",
    min_tank_size: "200 Litres",
    diet: "Carnivore (Beef heart blend, freeze-dried bloodworms, Discus granules)",
  },
  {
    id: "prod-koi-carp",
    name: "Japanese Patterned Koi Carp",
    category_id: "cat-freshwater",
    price: 350,
    unit: "per fish",
    description: "Graceful Kohaku and Sanke patterned koi carp ideal for garden ponds and oversized luxury tanks. Strong vitality and long lifespan.",
    tag: "Pond Special",
    image_url: "https://images.pexels.com/photos/14867656/pexels-photo-14867656.png?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 8,
    categories: defaultCategories[0],
    scientific_name: "Cyprinus carpio",
    care_level: "Easy",
    water_type: "Freshwater",
    temperament: "Peaceful",
    temp_range: "15°C - 26°C",
    ph_range: "7.0 - 8.0",
    min_tank_size: "300 Litres / Pond",
    diet: "Omnivore (Floating Koi sticks, wheatgerm)",
  },
  {
    id: "prod-halfmoon-betta",
    name: "Royal Blue Halfmoon Betta",
    category_id: "cat-freshwater",
    price: 180,
    unit: "per fish",
    description: "Spectacular 180-degree spread tail fin with iridescent sapphire and violet edges. Ideal single specimen for planted desktop nano aquariums.",
    tag: "Nano Favorite",
    image_url: "https://images.pexels.com/photos/18435512/pexels-photo-18435512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 9,
    categories: defaultCategories[0],
    scientific_name: "Betta splendens",
    care_level: "Easy",
    water_type: "Freshwater",
    temperament: "Aggressive",
    temp_range: "24°C - 29°C",
    ph_range: "6.5 - 7.5",
    min_tank_size: "15 Litres",
    diet: "Carnivore (Betta micro pellets, daphnia)",
  },

  // --- Marine Fish ---
  {
    id: "prod-rainbow-wrasse",
    name: "Rainbow Reef Wrasse",
    category_id: "cat-marine",
    price: 680,
    unit: "per fish",
    description: "Reef-safe marine wrasse with electric rainbow coloration that shimmers over live coral. Highly active swimmer that keeps coral free of flatworms.",
    tag: "Marine Exotic",
    image_url: "https://images.pexels.com/photos/36982268/pexels-photo-36982268.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 10,
    categories: defaultCategories[1],
    scientific_name: "Thalassoma lucasanum",
    care_level: "Intermediate",
    water_type: "Marine",
    temperament: "Semi-Aggressive",
    temp_range: "24°C - 27°C",
    ph_range: "8.1 - 8.4",
    min_tank_size: "150 Litres",
    diet: "Carnivore (Mysis shrimp, marine flakes)",
  },
  {
    id: "prod-orange-anthias",
    name: "Sunburst Orange Anthias",
    category_id: "cat-marine",
    price: 950,
    unit: "per fish",
    description: "Brilliant sunset orange and violet reef jewel. Brings continuous kinetic movement to saltwater display aquariums.",
    tag: "Reef Jewel",
    image_url: "https://images.pexels.com/photos/31807563/pexels-photo-31807563.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 11,
    categories: defaultCategories[1],
    scientific_name: "Pseudanthias squamipinnis",
    care_level: "Expert",
    water_type: "Marine",
    temperament: "Peaceful",
    temp_range: "23°C - 26°C",
    ph_range: "8.2 - 8.4",
    min_tank_size: "200 Litres",
    diet: "Planktivore (Copepods, enriched brine shrimp)",
  },
  {
    id: "prod-ocellaris-clown",
    name: "Ocellaris Clownfish (Nemo Pair)",
    category_id: "cat-marine",
    price: 850,
    unit: "per pair",
    description: "Captive-bred, hardy true clownfish pair with vivid orange stripes and black margins. Symbiotic with bubble tip anemones.",
    tag: "Saltwater Classic",
    image_url: "https://images.pexels.com/photos/36982268/pexels-photo-36982268.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 12,
    categories: defaultCategories[1],
    scientific_name: "Amphiprion ocellaris",
    care_level: "Easy",
    water_type: "Marine",
    temperament: "Peaceful",
    temp_range: "24°C - 28°C",
    ph_range: "8.1 - 8.4",
    min_tank_size: "60 Litres",
    diet: "Omnivore (Marine pellets, mysis, spirulina)",
  },

  // --- Aquatic Plants ---
  {
    id: "prod-anubias-nana",
    name: "Anubias Barteri var. Nana",
    category_id: "cat-plants",
    price: 90,
    unit: "per pot",
    description: "The indestructible aquascaping plant! Thick deep green leaves that thrive tied to driftwood or river rocks. Snail-treated and fully acclimated.",
    tag: "Hardy Plant",
    image_url: "https://images.pexels.com/photos/8970782/pexels-photo-8970782.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 13,
    categories: defaultCategories[2],
    scientific_name: "Anubias barteri var. nana",
    care_level: "Easy",
    water_type: "Planted",
    temperament: "Peaceful",
    temp_range: "20°C - 28°C",
    ph_range: "6.0 - 7.5",
    min_tank_size: "Any Tank Size",
    diet: "Liquid micro-nutrients & low lighting",
  },
  {
    id: "prod-java-fern",
    name: "Microsorum Java Fern Mat",
    category_id: "cat-plants",
    price: 75,
    unit: "per mat",
    description: "Broad leafy aquatic fern that purifies tank water, absorbs nitrates, and creates natural shelter for baby fish and shrimp.",
    tag: "Clean Water",
    image_url: "https://images.pexels.com/photos/31047030/pexels-photo-31047030.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 14,
    categories: defaultCategories[2],
    scientific_name: "Microsorum pteropus",
    care_level: "Easy",
    water_type: "Planted",
    temperament: "Peaceful",
    temp_range: "18°C - 28°C",
    ph_range: "6.0 - 7.5",
    min_tank_size: "Any Tank Size",
    diet: "Low to moderate lighting",
  },
  {
    id: "prod-rotala-red",
    name: "Rotala Rotundifolia Super Red",
    category_id: "cat-plants",
    price: 60,
    unit: "per bunch",
    description: "Fast-growing background stem plant that develops intense crimson-magenta tips under moderate to high lighting. Excellent for dense Dutch scapes.",
    tag: "Color Accent",
    image_url: "https://images.pexels.com/photos/12829679/pexels-photo-12829679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 15,
    categories: defaultCategories[2],
    scientific_name: "Rotala rotundifolia 'Red'",
    care_level: "Intermediate",
    water_type: "Planted",
    temperament: "Peaceful",
    temp_range: "22°C - 28°C",
    ph_range: "5.5 - 7.2",
    min_tank_size: "Any Tank Size",
    diet: "High light, iron dosing, CO2 recommended",
  },
  {
    id: "prod-monte-carlo",
    name: "Micranthemum Monte Carlo Carpet",
    category_id: "cat-plants",
    price: 130,
    unit: "per cup",
    description: "Lush, compact emerald carpet plant. Unlike Dwarf Baby Tears, Monte Carlo thrives even in moderate lighting and low-tech setups.",
    tag: "Carpeting Plant",
    image_url: "https://images.pexels.com/photos/8970782/pexels-photo-8970782.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 16,
    categories: defaultCategories[2],
    scientific_name: "Micranthemum tweediei",
    care_level: "Easy",
    water_type: "Planted",
    temperament: "Peaceful",
    temp_range: "20°C - 26°C",
    ph_range: "6.0 - 7.2",
    min_tank_size: "30 Litres",
    diet: "Nutrient soil, moderate light, liquid carbon",
  },
  {
    id: "prod-red-root-floater",
    name: "Red Root Floaters (Phyllanthus fluitans)",
    category_id: "cat-plants",
    price: 80,
    unit: "per portion",
    description: "Stunning floating rosette with ruby red feathery roots and olive-green heart leaves. Naturally sucks excess nitrates and blocks harsh surface light.",
    tag: "Surface Filter",
    image_url: "https://images.pexels.com/photos/31047030/pexels-photo-31047030.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 17,
    categories: defaultCategories[2],
    scientific_name: "Phyllanthus fluitans",
    care_level: "Easy",
    water_type: "Planted",
    temperament: "Peaceful",
    temp_range: "21°C - 29°C",
    ph_range: "6.0 - 7.5",
    min_tank_size: "Any Tank Size",
    diet: "Direct surface lighting & gentle flow",
  },

  // --- Tanks & Accessories ---
  {
    id: "prod-rimless-tank",
    name: "Ultra-Clear Low-Iron Rimless Tank (60cm / 64L)",
    category_id: "cat-tanks",
    price: 2400,
    unit: "per tank",
    description: "91% light-transmittance automotive-grade ultra-clear glass with precision 45-degree mitered silicone edges. High-density leveling foam mat included.",
    tag: "Premium Glass",
    image_url: "https://images.pexels.com/photos/37796017/pexels-photo-37796017.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 18,
    categories: defaultCategories[3],
    care_level: "Easy",
    water_type: "Freshwater",
    min_tank_size: "64 Litres Capacity",
  },
  {
    id: "prod-nano-tank",
    name: "Opti-White Nano Cube 30cm (27L)",
    category_id: "cat-tanks",
    price: 1350,
    unit: "per tank",
    description: "Compact desktop cube with diamond-beveled edges. Ideal for Betta fish, crystal shrimp colonies, or miniature planted scapes.",
    tag: "Desktop Favorite",
    image_url: "https://images.pexels.com/photos/37796017/pexels-photo-37796017.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 19,
    categories: defaultCategories[3],
    care_level: "Easy",
  },
  {
    id: "prod-canister-filter",
    name: "Multi-Stage External Canister Filter 1000 L/h",
    category_id: "cat-tanks",
    price: 3200,
    unit: "per unit",
    description: "Whisper-quiet filtration with 4 high-capacity media baskets. Includes sintered glass ceramic rings, coarse bio-sponge, and activated carbon.",
    tag: "Silent Bio-Filter",
    image_url: "https://images.pexels.com/photos/7254512/pexels-photo-7254512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 20,
    categories: defaultCategories[3],
    care_level: "Easy",
  },
  {
    id: "prod-led-light",
    name: "Full-Spectrum Aquascape LED 30W",
    category_id: "cat-tanks",
    price: 1100,
    unit: "per unit",
    description: "High PAR output with custom RGB diodes designed to bring out deep reds in fish and lush growth in aquatic plants. Includes moonlight mode.",
    tag: "High PAR",
    image_url: "https://images.pexels.com/photos/7254512/pexels-photo-7254512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 21,
    categories: defaultCategories[3],
    care_level: "Easy",
  },
  {
    id: "prod-dragon-stone",
    name: "Natural Dragon Stone Hardscape (5kg Pack)",
    category_id: "cat-tanks",
    price: 490,
    unit: "5kg pack",
    description: "Exotic clay-like textured volcanic rock filled with natural craters and crevices. Completely pH-neutral and ideal for mounting moss and Anubias.",
    tag: "Hardscape Natural",
    image_url: "https://images.pexels.com/photos/8970782/pexels-photo-8970782.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 22,
    categories: defaultCategories[3],
    care_level: "Easy",
  },

  // --- Fish Food ---
  {
    id: "prod-hikari-wafers",
    name: "Hikari Sinking Wafers 110g",
    category_id: "cat-food",
    price: 220,
    unit: "per pack",
    description: "Specially formulated for Bichirs, Loaches, and bottom-feeding catfish. Highly digestible formula enriched with pure spirulina and stabilized Vitamin C.",
    tag: "Bichir Diet",
    image_url: "https://images.pexels.com/photos/18435511/pexels-photo-18435511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 23,
    categories: defaultCategories[4],
  },
  {
    id: "prod-tetra-bits",
    name: "Tetra Bits Complete Granules 300g",
    category_id: "cat-food",
    price: 340,
    unit: "per pack",
    description: "Balanced staple food for Oscars, Discus, and all mid-water fish. Rich in carotenoids for radiant color enhancement and immune defense.",
    tag: "Daily Staple",
    image_url: "https://images.pexels.com/photos/18435511/pexels-photo-18435511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 24,
    categories: defaultCategories[4],
  },

  // --- Care & Health ---
  {
    id: "prod-aquasafe-conditioner",
    name: "AquaSafe Water Detox & Conditioner 250ml",
    category_id: "cat-care",
    price: 195,
    unit: "per bottle",
    description: "Essential for tap water water changes. Instantly neutralizes chlorine, chloramines, and binds toxic heavy metals while coating fish gills with protective colloids.",
    tag: "Essential",
    image_url: "https://images.pexels.com/photos/18435522/pexels-photo-18435522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 25,
    categories: defaultCategories[5],
  },
  {
    id: "prod-api-test-kit",
    name: "Freshwater Master Liquid Test Kit",
    category_id: "cat-care",
    price: 1650,
    unit: "per kit",
    description: "Professional aquarium laboratory test kit. Tests pH, High Range pH, Ammonia (NH3/NH4+), Nitrite (NO2-), and Nitrate (NO3-) over 800 times.",
    tag: "Lab Precision",
    image_url: "https://images.pexels.com/photos/18435522/pexels-photo-18435522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    is_active: true,
    sort_order: 26,
    categories: defaultCategories[5],
  },
];

export const defaultGallery: GalleryItem[] = [
  {
    id: "gal-1",
    image_url: "https://images.pexels.com/photos/31047030/pexels-photo-31047030.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Display Reef Tank with Live Soft Corals & Rainbow Wrasses",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "gal-2",
    image_url: "https://images.pexels.com/photos/12829679/pexels-photo-12829679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Lush 120cm Dutch Planted Aquascape with Cardinal Tetras",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "gal-3",
    image_url: "https://images.pexels.com/photos/31956913/pexels-photo-31956913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Albino Bichir & Dinosaur Eel Bottom Dweller Acclimatisation Bay",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "gal-4",
    image_url: "https://images.pexels.com/photos/8970782/pexels-photo-8970782.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Submerged Driftwood Scape with Quarantine-Cleared Anubias",
    sort_order: 4,
    is_active: true,
  },
  {
    id: "gal-5",
    image_url: "https://images.pexels.com/photos/36982268/pexels-photo-36982268.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Marine Coral Propagation & Live Invertebrate Showcase Wall",
    sort_order: 5,
    is_active: true,
  },
  {
    id: "gal-6",
    image_url: "https://images.pexels.com/photos/31807563/pexels-photo-31807563.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Golden Severum & Sunburst Anthias High-Clarity Showcase",
    sort_order: 6,
    is_active: true,
  },
  {
    id: "gal-7",
    image_url: "https://images.pexels.com/photos/37796017/pexels-photo-37796017.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Ultra-Clear Rimless Iwagumi Layout with Dragon Stone and Monte Carlo",
    sort_order: 7,
    is_active: true,
  },
  {
    id: "gal-8",
    image_url: "https://images.pexels.com/photos/14867656/pexels-photo-14867656.png?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Outdoor Bio-Filtered Japanese Koi Pond Designed for a Virudhunagar Villa",
    sort_order: 8,
    is_active: true,
  },
  {
    id: "gal-9",
    image_url: "https://images.pexels.com/photos/18435511/pexels-photo-18435511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "Red Tiger Oscar Specimen Tank with River Pebble Hardscape",
    sort_order: 9,
    is_active: true,
  },
  {
    id: "gal-10",
    image_url: "https://images.pexels.com/photos/7254512/pexels-photo-7254512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    caption: "High-Tech High-PAR LED Lighting Testing Station at Aqua Zoo Lab",
    sort_order: 10,
    is_active: true,
  },
];

export const defaultSettings: StoreSettings = {
  id: 1,
  store_name: "Sakthi's Aqua Zoo",
  location: "Virudhunagar",
  address: "No. 42, KVS Street, Near Old Bus Stand, Virudhunagar, Tamil Nadu 626001",
  phone: "+91 98765 43210",
  email: "hello@sakthisaquazoo.in",
  hours: "Mon–Sat: 9:30 AM – 8:30 PM · Sun: 10:00 AM – 6:00 PM",
  stat_species: 140,
  stat_plants: 55,
  stat_years: 8,
  announcement: "Special Offer: Free water testing and plant trimming guide with every live fish purchase!",
  whatsapp_number: "+919876543210",
};

// --- Additional rich data structures for individual pages ---

export interface TimelineEvent {
  year: string;
  title: string;
  description: string;
  milestone: string;
}

export const storeTimeline: TimelineEvent[] = [
  {
    year: "2017",
    title: "Founding in Virudhunagar",
    description: "Started by Mr. Sakthi as a dedicated quarantine and exotic freshwater breeding room for passionate regional fish hobbyists.",
    milestone: "10 display tanks, 25 species",
  },
  {
    year: "2019",
    title: "Aquatic Plant Nursery Launch",
    description: "Expanded facility to include 20 submerged propagation vats ensuring 100% snail-free, pest-treated planted tank foliage.",
    milestone: "35+ plant cultivars added",
  },
  {
    year: "2021",
    title: "Marine & Coral Propagation Wing",
    description: "Introduced dedicated saltwater systems with automated salinity control, protein skimmers, and sustainable captive-bred marine fish.",
    milestone: "First reef store in Virudhunagar district",
  },
  {
    year: "2023",
    title: "Turnkey Scaping & Commercial AMC",
    description: "Launched architectural aquascaping and bi-weekly maintenance contracts for corporate lobbies, hospitals, and luxury residences.",
    milestone: "500+ aquariums maintained",
  },
  {
    year: "2026",
    title: "Omni-Channel Digital Store & Express Delivery",
    description: "Launched web portal with live stock availability, digital water consultation, and oxygen-packed local door delivery.",
    milestone: "1,200+ hobbyists served regularly",
  },
];

export interface TeamMember {
  name: string;
  role: string;
  experience: string;
  specialty: string;
  bio: string;
}

export const storeTeam: TeamMember[] = [
  {
    name: "Sakthi Vignesh",
    role: "Founder & Master Aquarist",
    experience: "12+ Years Experience",
    specialty: "Monster Fish Biology & Disease Quarantine",
    bio: "Pioneered ethical fish quarantine in Virudhunagar. Passionate about Polypterus Bichirs and South American Cichlids.",
  },
  {
    name: "Dr. Ananya S.",
    role: "Aquatic Botanist & Plant Scaper",
    experience: "7+ Years Experience",
    specialty: "High-Tech Planted Tanks & CO2 Chemistry",
    bio: "Specializes in tissue-culture propagation, Dutch scapes, and micro-nutrient balance for vibrant red foliage.",
  },
  {
    name: "Muthu Kumar",
    role: "Lead Installation & Maintenance Engineer",
    experience: "8+ Years Experience",
    specialty: "Custom Plumbing, Sump Design & Water Chemistry",
    bio: "Oversees large centerpiece aquarium installations, automated filtration, and client maintenance contracts.",
  },
];

export interface ServicePackage {
  id: string;
  name: string;
  idealFor: string;
  price: string;
  features: string[];
  popular?: boolean;
}

export const servicePackages: ServicePackage[] = [
  {
    id: "pkg-basic",
    name: "Basic Care Visit",
    idealFor: "Home community tanks up to 100L",
    price: "₹499 / visit",
    features: [
      "25% - 40% Dechlorinated water exchange",
      "Gravel vacuuming & bottom detritus removal",
      "Glass scraping & interior algae scrubbing",
      "Filter sponge rinse in old tank water",
      "Basic pH, Ammonia & Nitrite testing",
    ],
  },
  {
    id: "pkg-planted",
    name: "Planted Scape Master Care",
    idealFor: "Planted aquariums & high-tech setups",
    price: "₹899 / visit",
    popular: true,
    features: [
      "Everything in Basic Care",
      "Precision plant trimming & moss pruning",
      "Liquid fertilizer & trace element dosing",
      "CO2 diffuser cleaning & bubble rate tuning",
      "Full 6-parameter lab-grade water testing",
      "Plant health & algae diagnostic report",
    ],
  },
  {
    id: "pkg-commercial",
    name: "Corporate & Villa AMC",
    idealFor: "Offices, clinics, large centerpiece tanks",
    price: "₹1,799 / month (Bi-weekly)",
    features: [
      "2 comprehensive visits every month",
      "All filter media replacements included",
      "Emergency 2-hour response for equipment failure",
      "Free replacement for quarantined livestock during AMC",
      "Automated lighting & feeder calibration",
      "Complete aesthetic showcase guarantee",
    ],
  },
];

export interface FAQItem {
  question: string;
  answer: string;
  category: "Fish Care" | "Purchasing & Delivery" | "Water & Tanks" | "Store Visit";
}

export const allFAQs: FAQItem[] = [
  {
    category: "Fish Care",
    question: "Why is a 14-day quarantine critical before adding fish to my tank?",
    answer: "Wild-caught and farm-bred fish frequently carry latent parasites (Ich, Velvet) and bacterial infections induced by shipping stress. At Sakthi's Aqua Zoo, every single specimen undergoes a minimum 14-day prophylactic regimen in isolated tanks so you only receive robust, sickness-free fish.",
  },
  {
    category: "Fish Care",
    question: "How do I feed and care for an Albino Bichir?",
    answer: "Albino Bichirs are peaceful bottom-dwelling carnivorous fish. They require sinking pellets (such as Hikari Sinking Wafers), freeze-dried bloodworms, or chopped prawn pieces. Because they breathe atmospheric air via lungs, ensure there is 2-3 inches of open air between the water surface and the tank lid.",
  },
  {
    category: "Water & Tanks",
    question: "What is the Nitrogen Cycle and how long does it take?",
    answer: "The Nitrogen Cycle is the process where beneficial nitrifying bacteria convert toxic fish waste (Ammonia) into Nitrite, and then into less toxic Nitrate. Establishing this biological filter in a new aquarium typically takes 2 to 4 weeks. We offer free water testing to verify your cycle before you add your first fish.",
  },
  {
    category: "Water & Tanks",
    question: "Can I use Virudhunagar tap water directly in my aquarium?",
    answer: "Tap water contains chlorine and chloramines which burn fish gills and kill beneficial bacteria. Always treat tap water with a quality dechlorinator (such as AquaSafe or Seachem Prime) before adding it to your aquarium. Bring a water sample to our store for free TDS and hardness evaluation.",
  },
  {
    category: "Purchasing & Delivery",
    question: "How do you package live fish for local delivery in Virudhunagar?",
    answer: "We pack all live livestock in heavy-duty double-layered poly bags filled with 1/3 water and 2/3 pure medical oxygen, packed inside insulated corrugated boxes. We guarantee 100% Live Arrival across Virudhunagar and neighboring areas.",
  },
  {
    category: "Purchasing & Delivery",
    question: "What is your shipping policy and delivery charge?",
    answer: "We offer FREE local delivery across Virudhunagar for all orders above ₹500. For orders under ₹500, a nominal delivery fee of ₹40 applies. Store pickup at our KVS Street location is always completely free.",
  },
  {
    category: "Store Visit",
    question: "Can I bring my aquarium water to the store for free testing?",
    answer: "Yes! Bring at least 100ml of your tank water in a clean, rinsed plastic or glass container (do not use soap). Our aquarists will test pH, Ammonia, Nitrite, Nitrate, and TDS on the spot and give you tailored advice for free.",
  },
  {
    category: "Store Visit",
    question: "What are your store hours and location?",
    answer: "We are located at No. 42, KVS Street, Near Old Bus Stand, Virudhunagar. We are open Monday to Saturday from 9:30 AM to 8:30 PM, and Sunday from 10:00 AM to 6:00 PM.",
  },
];
